title = "jxpiter"
baseURL = "https://jxpiterx.github.io/"

languageCode = 'en-us'
defaultContentLanguage = "en-us"

enableGitInfo = true
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]


[services]
  [services.googleAnalytics]
    id = ''

  [services.disqus]
    shortname = ''

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2
		endLevel = 4
		ordered = false

############################## English language ################################
[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content/en"
  weight = 1

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-us.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-us.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-us.params]
  sitename = "Jxpiter blog"
  defaultColor = "dark"
  description = "Minimal blog"
  mainSections = ['posts']
  toc = true
  tocOpen = false
  goToTop = true
  #additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = ""
  rssFeedDescription = "summary"

[Languages.en-us.params.author]
  avatar = "avatar.png"
  intro = "Welcome to my blog"
  name = "Jxpiter"
  description = "I'm Jxpiter, a French Cybersecurity student. Check my last post !"

[Languages.en-us.params.webmanifest]
  name = "sitename" 
  short_name = "sitename"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"


############################## French language ################################
[Languages.fr-fr]
  languageName = "French"
  languageCode = "fr-fr"
  contentDir = "content/fr"
  weight = 1

  [Languages.fr-fr.menu]
  [[Languages.fr-fr.menu.main]]
    pageRef="/"
    name = 'Accueil'
    url = '/'
    weight = 10
  [[Languages.fr-fr.menu.main]]
    pageRef="posts"
    name = 'Articles'
    url = '/posts/'
    weight = 20
  [[Languages.fr-fr.menu.main]]
    pageRef="about"
    name = 'À propos'
    url = '/about/'
    weight = 30

[Languages.fr-fr.params]
  sitename = "Jxpiter blog"
  defaultColor = "dark"
  description = "Minimal blog"
  mainSections = ['posts']
  toc = true
  tocOpen = false
  goToTop = true
  #additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = ""
  rssFeedDescription = "summary" 

[Languages.fr-fr.params.author]
  avatar = "avatar.png"
  intro = "Bienvenue sur mon blog"
  name = "Jxpiter"
  description = "Je suis Jxpiter, un étudiant Français en Cybersecurité. Regardez mes derniers Articles !"

[Languages.fr-fr.params.webmanifest]
  name = "sitename"
  short_name = "sitename"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"



#####################################################################################

[params.browserconfig]
  TileColor = "#2d89ef"

[[params.socialIcons]]
name = "github"
url = "https://github.com/JxpiterX"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/perret-mathieu"

[[params.socialIcons]]
name = "discord"
url = "https://discordapp.com/users/Jxpiter"